[pytest]
markers =
    smoke: Smoke tests
    regression: Regression tests
    critical: Critical path tests
    testops_demo: demo suite for TestOps presentations
    api: API checks
    ui: UI checks
    mobile: mobile checks
    contract: contract checks

addopts =
    -v
    --alluredir=allure-results
    --clean-alluredir
