[pytest]
markers =
    smoke: Smoke tests
    regression: Regression tests
    critical: Critical path tests
    testops_demo: demo suite for TestOps presentations
    unit: Unit checks
    api: API checks
    e2e: End-to-end checks

addopts =
    -v
    --alluredir=allure-results
    --clean-alluredir
