[pytest]
markers =
    smoke: Smoke tests
    regression: Regression tests
    critical: Critical path tests
    testops_demo: demo suite for TestOps presentations
    api: API checks
    ui: UI checks
    web: Web UI checks
    backend: Backend checks
    e2e: End-to-end checks
    integration: Integration checks
    business: Business rule checks
    mobile: mobile checks
    contract: contract checks

addopts =
    -v
    --alluredir=allure-results
    --clean-alluredir
